name: Lint with autopep8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # Run tests on every pull request to the main branch  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python3 -B --version
        python -m pip install --upgrade pip
        pip install --upgrade autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create post traces directory
      run: mkdir -p post_traces

    - name: Lint with autopep8
      run: |
        autopep8 --diff --exit-code --recursive . > post_traces/autopep8_trace.txt # running for all the files in the repo
      continue-on-error: true

    - name: Add and commit autopep8 trace
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Saving autopep8 trace"
    
    - name: Push changes to main
      run: git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
