name: Run Merge Sort Tests

on:
  push:
    branches:
      - main    # Run tests on every commit to the main branch
  pull_request:
    branches:
      - main    # Run tests on every pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3    # Check out the repository code
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'     # Specify the Python version

      - name: Install dependencies
        run: |
          pip install pytest
          if [ -f requirements.txt ]; pip install -r requirements.txt  # Install necessary dependencies

      - name: Run merge_sort test
        run: |
          pytest test_merge_sort.py        # Run your merge_sort test file using pytest