name: Python CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 pylint flake8 pytest # Or unittest if you use it

      - name: Run autopep8
        run: autopep8 --in-place hw2_debugging.py  # Format only merge_sort.py

      - name: Run pylint
        run: pylint hw2_debugging.py  # Analyze only merge_sort.py

      - name: Run flake8
        run: flake8 hw2_debugging.py  # Analyze only merge_sort.py

      - name: Run tests
        run: |
          pytest tests/   # Or use unittest discover tests/
