name: Lint with radon

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python3 -B --version
        python -m pip install --upgrade pip
        pip install --upgrade radon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create post traces directory
      run: mkdir -p post_traces

    - name: Lint with radon
      id: lint
      run: |
        radon raw . > post_traces/radon_raw.txt # running for all the files in the repo
        radon mi . > random_mi_report.txt
        radon cc . -s > radon_cc_report.txt
      continue-on-error: true # continue the execution even if there's a checkstyle error because we want to store the analysis trace in a txt file and push it to main in the next step.

    - name: Commit and save the file
      run: |
        git config --local user.email "salway.hrishikesh@gmail.com"
        git config --local user.name "hsalway1"
        if [ -n "$(git status --porcelain)" ]; then
          # Commit and push changes
          git add .
          git commit -m "Saving radon trace"
          git pull --rebase
          git push origin HEAD:main; fi

    - name: Fail if lint fails
      if: steps.lint.outcome == 'failure'
      run: exit 1 # fail the execution if "Lint with radon" step comes across a check style error.
